# ./manifests/api-gateway-app/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-app
  labels:
    app: api-gateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-app
  template:
    metadata:
      labels:
        app: api-gateway-app
    spec:
      containers:
        - name: api-gateway-app
          image: mouhameddiouf01/api-gateway-app:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-config